<a href="https://colab.research.google.com/github/leesm2504/ADALL_github/blob/main/Main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
Hello World!

SyntaxError: invalid syntax (25010090.py, line 1)

In [2]:
import pandas as pd
# Example: Replace this with the raw URL of your GitHub file
github_raw_url = 'https://raw.githubusercontent.com/leesm2504/ADALL_GitHub/refs/heads/main/laptop_prices_2024_sgd_TL.csv'
try:
  df = pd.read_csv(github_raw_url)
  print("Successfully loaded data from GitHub!")
  display(df.head())
except Exception as e:
  print(f"Error loading data: {e}")
  print("Please ensure the URL is correct and the file format is compatible with `pd.read_csv`.")

Successfully loaded data from GitHub!

,Brand,Model,CPU,GPU,RAM_GB,Storage_Type,Storage_GB,Touchscreen,Weight_kg,Screen_Size_inch,Discount_percent,Price_SGD,Brand_Discount,Member_Discount
0,Acer,Aspire 5,Intel i9-14900HK,NVIDIA RTX 4070,64,SSD,256,False,1.56,16.0,3.27,2413.36,5,144.80
1,Acer,Nitro 5,AMD Ryzen 9 8900HX,AMD Radeon 780M,32,SSD,1024,True,1.45,14.0,5.03,1773.75,5,124.16
2,Acer,Nitro 5,AMD Ryzen 5 8600H,NVIDIA RTX 4050,32,SSD,2048,False,1.34,14.0,4.41,1634.07,5,98.04
3,Acer,TravelMate P6,Intel Core Ultra 7 15500H,NVIDIA RTX 4060,16,SSD,4096,True,1.18,13.3,2.16,2362.59,5,118.13
4,Acer,Predator Helios 300,Intel i7-14800H,NVIDIA RTX 4070,8,SSD,1024,True,1.31,14.0,6.93,2218.55,5,155.30

In [3]:
import pandas as pd
# Example: Replace this with the raw URL of your GitHub file
github_raw_url = 'https://raw.githubusercontent.com/leesm2504/ADALL_github/refs/heads/main/laptop_prices_2024_sgd_TL.csv'
try:
    df = pd.read_csv(github_raw_url)
    print("Successfully loaded data from GitHub!")
    display(df.head())
except Exception as e:
    print(f"Error loading data: {e}")
    print("Please ensure the URL is correct and the file format is compatible with `pd.read_csv`.")

Successfully loaded data from GitHub!

,Brand,Model,CPU,GPU,RAM_GB,Storage_Type,Storage_GB,Touchscreen,Weight_kg,Screen_Size_inch,Discount_percent,Price_SGD,Brand_Discount,Member_Discount
0,Acer,Aspire 5,Intel i9-14900HK,NVIDIA RTX 4070,64,SSD,256,False,1.56,16.0,3.27,2413.36,5,144.80
1,Acer,Nitro 5,AMD Ryzen 9 8900HX,AMD Radeon 780M,32,SSD,1024,True,1.45,14.0,5.03,1773.75,5,124.16
2,Acer,Nitro 5,AMD Ryzen 5 8600H,NVIDIA RTX 4050,32,SSD,2048,False,1.34,14.0,4.41,1634.07,5,98.04
3,Acer,TravelMate P6,Intel Core Ultra 7 15500H,NVIDIA RTX 4060,16,SSD,4096,True,1.18,13.3,2.16,2362.59,5,118.13
4,Acer,Predator Helios 300,Intel i7-14800H,NVIDIA RTX 4070,8,SSD,1024,True,1.31,14.0,6.93,2218.55,5,155.30

In [1]:
from google.colab import userdata
from openai import OpenAI


# Load key from Google Colab Secrets
api_key = userdata.get('OPENAI_API_KEY')

client = OpenAI(
    # This is the default and can be omitted
    api_key=api_key,
)

response = client.responses.create(
    model="gpt-5-mini",
    instructions="You are a data analyst expert who uses Python.",
    input="What is Exploratory Data Analysis?",
)

print(response.output_text)

Exploratory Data Analysis (EDA) is the process of summarizing, visualizing, and investigating a dataset to understand its main characteristics, detect patterns, spot anomalies, check assumptions, and generate hypotheses before formal modeling. It’s about learning the data so you can make informed decisions about cleaning, feature engineering, and modeling.

Key goals
- Understand structure: types, shapes, ranges, and missingness.
- Summarize distributions and central tendencies.
- Detect outliers, anomalies, and data quality issues.
- Reveal relationships and correlations between variables.
- Inform feature creation, selection, and modeling strategy.
- Generate and validate hypotheses.

Typical EDA workflow
1. Define questions and the target/metrics you care about.
2. Load data and get a quick overview (rows, columns, dtypes).
3. Summarize numerically (describe, counts, groupby aggregates).
4. Check missing values and inconsistent entries.
5. Visualize distributions and relationships (univariate and multivariate plots).
6. Detect and investigate outliers and anomalies.
7. Transform/engineer features (scaling, log transforms, encoding).
8. Reassess after cleaning/transformations and iterate.
9. Document findings and next steps for modeling.

Common tasks & techniques
- Data shape and types: head(), info(), dtypes
- Summary statistics: describe(), value_counts(), groupby().agg()
- Missingness: isnull().sum(), percentage missing, missingness patterns
- Univariate plots: histogram, KDE, boxplot, bar chart
- Bivariate plots: scatterplot, line plot, stripplot, violin plot
- Multivariate: pairplot, heatmap of correlations, scatter matrix
- Categorical analysis: cross-tabs, pivot tables, stacked bars
- Outlier detection: IQR rule, z-scores, visualization with boxplots
- Feature relationships: correlation, conditional averages, partial dependence
- Dimensionality reduction / structure: PCA, t-SNE, UMAP
- Clustering for structure: KMeans, hierarchical clustering, clustermap

Python tools commonly used
- pandas, numpy for data manipulation
- matplotlib, seaborn for static visualization
- plotly, bokeh for interactive plots
- missingno for visualizing missing data
- scikit-learn for PCA, clustering, scaling
- statsmodels for statistical summaries/tests

Minimal Python EDA example
(quick checklist you can run and build from)
```
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('data.csv')

# Overview
print(df.shape)
print(df.info())
print(df.describe())

# Missingness
print(df.isnull().mean().sort_values(ascending=False).head())

# Univariate
df['numeric_col'].hist(bins=40)
sns.boxplot(x=df['numeric_col'])

# Categorical
print(df['category_col'].value_counts(normalize=True))

# Relationships
sns.scatterplot(x='num1', y='num2', hue='target', data=df)
sns.heatmap(df.select_dtypes('number').corr(), annot=True, fmt='.2f')

# Quick group summary
print(df.groupby('category_col')['target'].agg(['count','mean']))
```

Best practices
- Start with questions/objectives and iterate; don’t rush to modeling.
- Visualize distributions, not just summary statistics.
- Work on a sample for speed, but validate findings on full data.
- Log transformations or binning can reveal hidden patterns.
- Record assumptions, data-cleaning steps, and notable findings for reproducibility.
- Watch for leakage (features that wouldn’t be available in production) and class imbalance.

In short: EDA is an investigative, iterative process that combines descriptive statistics and visualization to understand data quality and structure, guide feature engineering, and shape modeling choices.

In [4]:
df.info ()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Brand             1000 non-null   object
 1   Model             1000 non-null   object
 2   CPU               1000 non-null   object
 3   GPU               1000 non-null   object
 4   RAM_GB            1000 non-null   int64
 5   Storage_Type      1000 non-null   object
 6   Storage_GB        1000 non-null   int64
 7   Touchscreen       1000 non-null   bool
 8   Weight_kg         1000 non-null   float64
 9   Screen_Size_inch  1000 non-null   float64
 10  Discount_percent  1000 non-null   float64
 11  Price_SGD         1000 non-null   float64
 12  Brand_Discount    1000 non-null   int64
 13  Member_Discount   1000 non-null   float64
dtypes: bool(1), float64(5), int64(3), object(5)
memory usage: 102.7+ KB

In [5]:
df.duplicated ()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [6]:
# Convert the first few rows to a string to send to OpenAI
data_preview = df.head(10).to_csv(index=False)
print(data_preview)



response = client.responses.create(
    model="gpt-4o-mini",
    instructions="You are an expert data scientist with extensive knowledge of predictive analysis and linear regression.",
    input=f"Dataset: Iris flower classification (150 samples, 4 features, 3 classes)\nHere are the first 10 rows of the dataset:\n{data_preview}]",
)
print(response.output_text)

Brand,Model,CPU,GPU,RAM_GB,Storage_Type,Storage_GB,Touchscreen,Weight_kg,Screen_Size_inch,Discount_percent,Price_SGD,Brand_Discount,Member_Discount
Acer,Aspire 5,Intel i9-14900HK,NVIDIA RTX 4070,64,SSD,256,False,1.56,16.0,3.27,2413.36,5,144.8
Acer,Nitro 5,AMD Ryzen 9 8900HX,AMD Radeon 780M,32,SSD,1024,True,1.45,14.0,5.03,1773.75,5,124.16
Acer,Nitro 5,AMD Ryzen 5 8600H,NVIDIA RTX 4050,32,SSD,2048,False,1.34,14.0,4.41,1634.07,5,98.04
Acer,TravelMate P6,Intel Core Ultra 7 15500H,NVIDIA RTX 4060,16,SSD,4096,True,1.18,13.3,2.16,2362.59,5,118.13
Acer,Predator Helios 300,Intel i7-14800H,NVIDIA RTX 4070,8,SSD,1024,True,1.31,14.0,6.93,2218.55,5,155.3
Acer,Aspire 5,Intel i9-14900HK,NVIDIA RTX 4080,32,SSD,256,False,3.34,17.3,8.94,2224.12,5,155.69
Acer,TravelMate P6,Intel i9-14900HK,NVIDIA RTX 4080,128,SSD,1024,True,1.11,13.3,11.72,3016.36,5,211.15
Acer,Predator Helios 300,Intel Core Ultra 9 15700H,NVIDIA RTX 4070,16,SSD,2048,True,1.29,13.3,8.84,2579.29,5,180.55
Acer,Swift 3,Intel i5-14500H,NVIDIA RTX 4050,64,SSD,4096,False,1.4,13.3,6.92,1976.94,5,98.85
Acer,Nitro 5,Intel Core Ultra 9 15700H,NVIDIA RTX 4070,16,SSD,2048,False,1.15,13.3,5.25,2538.34,5,152.3

It seems you've provided a dataset concerning laptops, including various features such as CPU, GPU, RAM, storage type, and prices. However, your initial reference to the Iris flower dataset suggests a categorization task, typically aimed at classifying flower types based on petal and sepal measurements.

To assist you effectively with your laptop dataset, we can consider potential data explorations, analyses, or predictive modeling techniques based on the values and features in the provided data. Here are some steps we might consider:

### Data Exploration

1. **Summary Statistics**:
   - Generate statistics for numerical columns such as `Price_SGD`, `RAM_GB`, `Weight_kg`, etc.
   - Check for missing values.

2. **Correlations**:
   - Examine correlations between features, particularly between `Discount_percent` and `Price_SGD`, and how they relate with other features.

3. **Visualizations**:
   - Histograms for the distribution of numerical features.
   - Boxplots to compare price distributions across different brands.
   - Scatter plots to visualize relationships, e.g., price vs. RAM.

### Predictive Modeling

1. **Target Variable**:
   - Decide on a target variable for prediction. For instance, you might want to predict `Price_SGD` based on other features.

2. **Data Preprocessing**:
   - Encode categorical variables like `Brand`, `Model`, `Storage_Type`, and `Touchscreen` into suitable numerical formats (one-hot encoding or label encoding).
   - Normalize/standardize numerical features if necessary.

3. **Model Selection**:
   - Choose a predictive model. Since you mentioned linear regression:
     - Use multiple linear regression if your target variable is continuous (e.g., predicting price).
     - If you are classifying (e.g., prediction of `Brand` or `Discount`), consider logistic regression or decision trees.

4. **Model Evaluation**:
   - Split the dataset into training and testing samples.
   - Use metrics such as RMSE (Root Mean Square Error) for regression tasks or accuracy and F1-score for classification tasks to evaluate performance.

5. **Hyperparameter Tuning**:
   - Optimize model parameters using techniques like Grid Search or Random Search based on cross-validation.

### Practical Code Examples
Here is a pseudo-code outline for implementing a linear regression model using Python (with libraries like pandas and scikit-learn):

```python
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Load data
data = pd.read_csv('path_to_laptop_dataset.csv')

# Preprocess data
data = pd.get_dummies(data, columns=['Brand', 'Model', 'Storage_Type'], drop_first=True)
X = data.drop('Price_SGD', axis=1)
y = data['Price_SGD']

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the model
model = LinearRegression()
model.fit(X_train, y_train)

# Predict and evaluate
predictions = model.predict(X_test)
mse = mean_squared_error(y_test, predictions)
print(f'Mean Squared Error: {mse}')
```

### Conclusion
By following these steps, you can uncover insights from your laptop dataset or develop a predictive model based on it. If you have specific questions or tasks in mind, feel free to share!

In [7]:
# Convert the first few rows to a string to send to OpenAI
data_preview = df.head(10).to_csv(index=False)
print(data_preview)

response = client.responses.create(
  model="gpt-5-mini",
  instructions="You are an expert data scientist with extensive knowledge of predictive analysis and linear regression.",
  input=f"Dataset: Laptop Price Prdiction (1000 samples, 14 features, traget is Price_SGD)\nHere are the first 10 rows of the dataset:\n{data_preview}]",
)
print(response.output_text)

Brand,Model,CPU,GPU,RAM_GB,Storage_Type,Storage_GB,Touchscreen,Weight_kg,Screen_Size_inch,Discount_percent,Price_SGD,Brand_Discount,Member_Discount
Acer,Aspire 5,Intel i9-14900HK,NVIDIA RTX 4070,64,SSD,256,False,1.56,16.0,3.27,2413.36,5,144.8
Acer,Nitro 5,AMD Ryzen 9 8900HX,AMD Radeon 780M,32,SSD,1024,True,1.45,14.0,5.03,1773.75,5,124.16
Acer,Nitro 5,AMD Ryzen 5 8600H,NVIDIA RTX 4050,32,SSD,2048,False,1.34,14.0,4.41,1634.07,5,98.04
Acer,TravelMate P6,Intel Core Ultra 7 15500H,NVIDIA RTX 4060,16,SSD,4096,True,1.18,13.3,2.16,2362.59,5,118.13
Acer,Predator Helios 300,Intel i7-14800H,NVIDIA RTX 4070,8,SSD,1024,True,1.31,14.0,6.93,2218.55,5,155.3
Acer,Aspire 5,Intel i9-14900HK,NVIDIA RTX 4080,32,SSD,256,False,3.34,17.3,8.94,2224.12,5,155.69
Acer,TravelMate P6,Intel i9-14900HK,NVIDIA RTX 4080,128,SSD,1024,True,1.11,13.3,11.72,3016.36,5,211.15
Acer,Predator Helios 300,Intel Core Ultra 9 15700H,NVIDIA RTX 4070,16,SSD,2048,True,1.29,13.3,8.84,2579.29,5,180.55
Acer,Swift 3,Intel i5-14500H,NVIDIA RTX 4050,64,SSD,4096,False,1.4,13.3,6.92,1976.94,5,98.85
Acer,Nitro 5,Intel Core Ultra 9 15700H,NVIDIA RTX 4070,16,SSD,2048,False,1.15,13.3,5.25,2538.34,5,152.3

Thanks — this is a good starting sample. I can help you build a strong predictive workflow for Price_SGD (baseline models, improvements, and evaluation). Below I give a concise recommended analysis plan, practical preprocessing/feature-engineering tips for this dataset, and example Python code you can run to get a robust baseline linear model and regularized alternatives. Tell me if you prefer R instead of Python or want me to run these steps for you (if you can share the whole dataset).

1) Quick analysis plan (high level)
- EDA: distributions, missing values, correlations (esp. Price vs Discount_percent, Brand_Discount, Member_Discount), check skewness of Price_SGD.
- Preprocessing: handle categorical features (Brand, Model, CPU, GPU, Storage_Type, Touchscreen), scale numeric features (RAM_GB, Storage_GB, Weight_kg, Screen_Size_inch, Discount_percent, Brand_Discount, Member_Discount).
- Feature engineering: encode high-cardinality cats (Model/CPU/GPU) carefully, interaction terms (e.g., CPU*GPU, RAM*Storage), log-transform target if skewed.
- Modeling: baseline LinearRegression, then Ridge/Lasso, and tree-based models (RandomForest, XGBoost/CatBoost) for comparison.
- Validation: train/test split with cross-validation (k=5 or 10). Use metrics RMSE, MAE, R^2. For target encoding use nested CV or K-fold encoding to avoid leakage.
- Diagnostics: residual plots, VIF for multicollinearity, feature importance, partial dependence for top features.

2) Preprocessing & encoding recommendations (dataset-specific)
- Brand: low cardinality → one-hot encoding.
- Model, CPU, GPU: high cardinality → don't blind one-hot (will explode). Options:
  - Target encoding (with K-fold to avoid leakage).
  - Frequency encoding (replace category with its count/frequency).
  - Hashing or embeddings for complex models.
  - For linear models, target/frequency encoding often works best.
- Storage_Type and Touchscreen: one-hot / binary.
- Numeric features: scale (StandardScaler) for linear models; for tree models scaling not required.
- Outliers/missing: check and cap or transform as appropriate.
- Consider log(Price_SGD) if price is skewed — improves normality and stabilizes variance.

3) Baseline Python code (pandas + scikit-learn)
This provides a robust baseline: one-hot low-cardinality cats, target encoding for high-cardinality cats using K-fold encoding to avoid leakage, scaling, and cross-validated evaluation for LinearRegression and Ridge/Lasso.

Note: you need category_encoders or you can implement KFold target encoding manually. Below I include an implementation of K-fold target encoding to avoid extra packages.

```python
import numpy as np
import pandas as pd
from sklearn.model_selection import KFold, train_test_split, cross_val_score, GridSearchCV
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# load data
df = pd.read_csv("laptops.csv")  # replace with your filename
y = df['Price_SGD']
X = df.drop(columns=['Price_SGD'])

# basic feature lists
high_card = ['Model','CPU','GPU']
low_card = ['Brand','Storage_Type','Touchscreen']
num_feats = ['RAM_GB','Storage_GB','Weight_kg','Screen_Size_inch','Discount_percent','Brand_Discount','Member_Discount']

# Simple KFold target encoder (out-of-fold mean)
def kfold_target_encode(train_X, train_y, cols, n_splits=5, random_state=0):
    X = train_X.copy()
    for col in cols:
        col_encoded = np.zeros(len(X))
        kf = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
        for train_index, val_index in kf.split(X):
            tr_idx, val_idx = train_index, val_index
            means = train_y.iloc[tr_idx].groupby(train_X.iloc[tr_idx][col]).mean()
            # map means to validation rows; missing categories -> global mean
            col_encoded[val_idx] = train_X.iloc[val_idx][col].map(means).fillna(train_y.mean()).values
        X[col + '_te'] = col_encoded
    return X

# We'll do a train/test split and apply kfold-encoding only on training fold, then map to test using training global means.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Encode high-cardinality with KFold target encoding on training set
X_train_te = kfold_target_encode(X_train, y_train, high_card, n_splits=5, random_state=42)

# Compute global mapping from whole train to apply to test set
global_maps = {}
for col in high_card:
    global_maps[col] = y_train.groupby(X_train[col]).mean()

X_test_te = X_test.copy()
for col in high_card:
    X_test_te[col + '_te'] = X_test_te[col].map(global_maps[col]).fillna(y_train.mean())

# Build preprocessing: one-hot for low-card, scale for numeric + use the created *_te columns and drop original high-card columns
te_cols = [c + '_te' for c in high_card]
preproc = ColumnTransformer([
    ('ohe_low', OneHotEncoder(handle_unknown='ignore', sparse=False), low_card),
    ('num', StandardScaler(), num_feats),
    # passthrough target-encoded cols
], remainder='passthrough')

# prepare final train/test arrays (drop original high-card columns, keep te cols)
X_train_final = X_train_te.drop(columns=high_card)
X_test_final = X_test_te.drop(columns=high_card)

# ensure the target-encoded columns are present in rearranged dataframes
# Build pipeline with LinearRegression
pipe = Pipeline([
    ('pre', preproc),
    ('lr', LinearRegression())
])

# cross-validated RMSE on training set
cv_scores = cross_val_score(pipe, X_train_final, y_train, scoring='neg_root_mean_squared_error', cv=5)
print("CV RMSE (Linear):", -cv_scores.mean(), "±", cv_scores.std())

# Fit and evaluate on hold-out
pipe.fit(X_train_final, y_train)
y_pred = pipe.predict(X_test_final)
print("Test RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("Test MAE:", mean_absolute_error(y_test, y_pred))
print("Test R2:", r2_score(y_test, y_pred))

# Try Ridge and Lasso using GridSearchCV
param_grid = {'alpha': [0.01, 0.1, 1, 10, 100]}
ridge = Pipeline([('pre', preproc), ('model', Ridge())])
ridge_cv = GridSearchCV(ridge, {'model__alpha':[0.01,0.1,1,10,100]}, scoring='neg_root_mean_squared_error', cv=5)
ridge_cv.fit(X_train_final, y_train)
print("Best Ridge alpha:", ridge_cv.best_params_, "CV RMSE:", -ridge_cv.best_score_)
print("Ridge Test RMSE:", np.sqrt(mean_squared_error(y_test, ridge_cv.predict(X_test_final))))
```

Notes about the code:
- The KFold target encoder implemented above avoids leakage during training CV. When applying to test, we map using the training-group means and fall back to training global mean if unseen categories appear.
- If you prefer simplicity, you can use pandas.get_dummies for all categorical columns — but with Model/CPU/GPU that will blow up features.
- For final production use consider category_encoders library or CatBoost/LightGBM which handle categorical features natively.

4) Modeling tips & diagnostics
- Try log(Price_SGD) as target if distribution skewed: model log-price, evaluate RMSE on log scale, then exponentiate predictions (beware bias; use smearing correction if needed).
- Use Ridge if multicollinearity present; check VIF for numeric features.
- For interpretable linear models, after target encoding, inspect coefficients; for tree models inspect SHAP values for feature impact.
- Ensemble: stacking linear+tree often improves accuracy.

5) Next steps / What I can do for you
- I can produce: a full notebook implementing the above, plus RandomForest/XGBoost baselines and hyperparameter tuning.
- Or I can run an EDA and highlight the most predictive features if you share the full dataset.
- Do you want: (A) runnable notebook/code only, (B) trained model + performance report, or (C) EDA + recommendations?

Tell me which output you want and whether Python / sklearn is fine. If you want me to proceed, upload the full CSV (or allow me to fetch it) and I’ll run the full pipeline and return results.

In [8]:
data_preview = df.head(10).to_json(orient='records')
print(data_preview)

[{"Brand":"Acer","Model":"Aspire 5","CPU":"Intel i9-14900HK","GPU":"NVIDIA RTX 4070","RAM_GB":64,"Storage_Type":"SSD","Storage_GB":256,"Touchscreen":false,"Weight_kg":1.56,"Screen_Size_inch":16.0,"Discount_percent":3.27,"Price_SGD":2413.36,"Brand_Discount":5,"Member_Discount":144.8},{"Brand":"Acer","Model":"Nitro 5","CPU":"AMD Ryzen 9 8900HX","GPU":"AMD Radeon 780M","RAM_GB":32,"Storage_Type":"SSD","Storage_GB":1024,"Touchscreen":true,"Weight_kg":1.45,"Screen_Size_inch":14.0,"Discount_percent":5.03,"Price_SGD":1773.75,"Brand_Discount":5,"Member_Discount":124.16},{"Brand":"Acer","Model":"Nitro 5","CPU":"AMD Ryzen 5 8600H","GPU":"NVIDIA RTX 4050","RAM_GB":32,"Storage_Type":"SSD","Storage_GB":2048,"Touchscreen":false,"Weight_kg":1.34,"Screen_Size_inch":14.0,"Discount_percent":4.41,"Price_SGD":1634.07,"Brand_Discount":5,"Member_Discount":98.04},{"Brand":"Acer","Model":"TravelMate P6","CPU":"Intel Core Ultra 7 15500H","GPU":"NVIDIA RTX 4060","RAM_GB":16,"Storage_Type":"SSD","Storage_GB":4096,"Touchscreen":true,"Weight_kg":1.18,"Screen_Size_inch":13.3,"Discount_percent":2.16,"Price_SGD":2362.59,"Brand_Discount":5,"Member_Discount":118.13},{"Brand":"Acer","Model":"Predator Helios 300","CPU":"Intel i7-14800H","GPU":"NVIDIA RTX 4070","RAM_GB":8,"Storage_Type":"SSD","Storage_GB":1024,"Touchscreen":true,"Weight_kg":1.31,"Screen_Size_inch":14.0,"Discount_percent":6.93,"Price_SGD":2218.55,"Brand_Discount":5,"Member_Discount":155.3},{"Brand":"Acer","Model":"Aspire 5","CPU":"Intel i9-14900HK","GPU":"NVIDIA RTX 4080","RAM_GB":32,"Storage_Type":"SSD","Storage_GB":256,"Touchscreen":false,"Weight_kg":3.34,"Screen_Size_inch":17.3,"Discount_percent":8.94,"Price_SGD":2224.12,"Brand_Discount":5,"Member_Discount":155.69},{"Brand":"Acer","Model":"TravelMate P6","CPU":"Intel i9-14900HK","GPU":"NVIDIA RTX 4080","RAM_GB":128,"Storage_Type":"SSD","Storage_GB":1024,"Touchscreen":true,"Weight_kg":1.11,"Screen_Size_inch":13.3,"Discount_percent":11.72,"Price_SGD":3016.36,"Brand_Discount":5,"Member_Discount":211.15},{"Brand":"Acer","Model":"Predator Helios 300","CPU":"Intel Core Ultra 9 15700H","GPU":"NVIDIA RTX 4070","RAM_GB":16,"Storage_Type":"SSD","Storage_GB":2048,"Touchscreen":true,"Weight_kg":1.29,"Screen_Size_inch":13.3,"Discount_percent":8.84,"Price_SGD":2579.29,"Brand_Discount":5,"Member_Discount":180.55},{"Brand":"Acer","Model":"Swift 3","CPU":"Intel i5-14500H","GPU":"NVIDIA RTX 4050","RAM_GB":64,"Storage_Type":"SSD","Storage_GB":4096,"Touchscreen":false,"Weight_kg":1.4,"Screen_Size_inch":13.3,"Discount_percent":6.92,"Price_SGD":1976.94,"Brand_Discount":5,"Member_Discount":98.85},{"Brand":"Acer","Model":"Nitro 5","CPU":"Intel Core Ultra 9 15700H","GPU":"NVIDIA RTX 4070","RAM_GB":16,"Storage_Type":"SSD","Storage_GB":2048,"Touchscreen":false,"Weight_kg":1.15,"Screen_Size_inch":13.3,"Discount_percent":5.25,"Price_SGD":2538.34,"Brand_Discount":5,"Member_Discount":152.3}]